 stages:
  - task-1:
    name: Here is the task 1
    package: "ticker"
    params:
      totalTicks: 10
      msBetweenTicks: 1000
      msgOnTick: "I am a tick"
      msgEndTicking: "I am done ticking"
  - task-2:
    name: Here is the task 2
    package: "ticker"
    params:
      totalTicks: 10
      msBetweenTicks: 500
      msgOnTick: "I am another tick"
      msgEndTicking: "I am also done ticking"
  - task-3:
    name: Here is the task 3
    package: "container"
    params:
      id: 1
      layout: "SharedMap"
      text: "SharedString"
      isCreate: true
  - task-4:
    name: Here is the task 3
    package: "container"
    params:
      id: 2
      layout: "SharedMap"
      text: "SharedString"
      isCreate: false

