 stages:
  - task-1:
    name: Here is the task 1
    package: "ticker"
    params:
      totalTicks: 2
      msBetweenTicks: 1000
      msgOnTick: "I am ticking every 1000ms"
      msgEndTicking: "I done ticking"
  - task-2:
    name: Here is the task 2
    package: "ticker"
    params:
      totalTicks: 2
      msBetweenTicks: 500
      msgOnTick: "I am ticking every 500ms"
      msgEndTicking: "I am also done ticking"
  - task-3:
    name: Create azure client
    package: azureFactory
    out: $(Client1)
    params:
      type: local
      endpoint: http://localhost:7070
      userId: SomeUserId;
      userName: SomeName;
  - task-4:
    name: Create container
    package: containerFactory
    out: $(Container1)
    params:
      client: $(Client1)
      initialObjects:
        key1: SharedMap
        key2: SharedMap
  - task-5:
    name: Create traffic
    package: containerTrafficRunner
    params:
      client: $(Client1)
      docId: $(Container1)
      initialObjects:
        key1: SharedMap
        key2: SharedMap
      actions:
      - action1:
        action: set
        target: key1
        key: a
        value: test1
      - action2:
        action: set
        target: key2
        key: b
        value: test2
      flushAfterAction: true
      flushAfterRun: true
  - task-6:
    name: Create traffic
    package: containerTrafficValidator
    params:
      client: $(Client1)
      docId: $(Container1)
      initialObjects:
        key1: SharedMap
        key2: SharedMap
      actions:
      - action1:
        action: get
        target: key1
        key: a
        expectedVal: test1
      - action2:
        action: get
        target: key2
        key: b
        expectedVal: test2
